= Exercise 1.1 - Installing Ansible Tower

In this exercise, we are going to get Ansible Tower installed on your control node

==== *+++<u>Step 1:</u>+++* 
ssh into your control node

*$ ssh <username>@<IP of control node>*

==== *+++<u>Step 2:</u>+++* 
Change directories to /tmp

*$ cd /tmp*

==== *+++<u>Step 3:</u>+++* 
Download the latest Ansible Tower package

*$ curl -O https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz*

==== *+++<u>Step 4:</u>+++* 
Untar and unzip the package file

*$ tar xvfz /tmp/ansible-tower-setup-*  (Name of tar file that was downloaded)*

==== *+++<u>Step 5:</u>+++* 
Change directories into the ansible tower package

*$ cd /tmp/ansible-tower-setup-*

==== *+++<u>Step 6:</u>+++* 
Using an editor of your choice, open the inventory file

*$ vi inventory*

==== *+++<u>Step 7:</u>+++* 
fill a few variables out in an inventory file: admin_password, rabbitmq_password, pg_password

[tower] +
localhost ansible_connection=local

[database]

[all:vars] +
*admin_password='ansibleWS'*

pg_host='' +
pg_port=''

pg_database='awx' +
pg_username='awx' +
*pg_password='ansibleWS'*

rabbitmq_port=5672 +
rabbitmq_vhost=tower +
rabbitmq_username=tower +
*rabbitmq_password='ansibleWS'* +
rabbitmq_cookie=cookiemonster


....
# Needs to be true for fqdns and ip addresses
rabbitmq_use_long_name=false
....

==== *+++<u>Step 8:</u>+++* 
run the Ansible Tower setup script

*$ sudo ./setup.sh*

Step 8 will take approx. 10-15 minutes to complete. This may be a good time to take a break.

At this point, your Ansible Tower installation should be complete. 

You can access Tower at http://<IP-of-your-control-node>;

Ensuring Installation Success

You know you were successful if you are able to browse to your Ansible Towers url (control nodes IP address) and see a login screen.


link:Configuring-Ansible-Tower.adoc[Next Lab]

link:TableOfContents.adoc[Table Of Contents]